import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiTailwindcss,
  SiBootstrap,
  SiVite,
  SiFlutter,
  SiDart,
  SiPostgresql,
  SiMysql,
  SiPrisma,
  SiDjango,
  SiPython,
  SiLaravel,
  SiGo,
  SiNextdotjs,
  SiSocketdotio,
  SiDocker,
  SiFigma,
  SiRedux,
  SiGithub,
} from 'react-icons/si'
import { Braces, KeyRound } from 'lucide-react'

type IconType = React.ComponentType<{ size?: number | string; className?: string }>

export const TECH_ICONS: Record<string, IconType> = {
  React: SiReact,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  'Node.js': SiNodedotjs,
  'Tailwind CSS': SiTailwindcss,
  Bootstrap: SiBootstrap,
  Vite: SiVite,
  Flutter: SiFlutter,
  Dart: SiDart,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Prisma: SiPrisma,
  Django: SiDjango,
  Python: SiPython,
  Laravel: SiLaravel,
  Go: SiGo,
  'Next.js': SiNextdotjs,
  'Socket.io': SiSocketdotio,
  Docker: SiDocker,
  Figma: SiFigma,
  Redux: SiRedux,
  GitHub: SiGithub,
  Git: SiGithub,
  'REST API': Braces,
  'JWT Auth': KeyRound,
}