export const profile = {
  name: 'Setya Ardi Kurniawan',
  shortName: 'Ardi',
  role: 'Fullstack Developer',
  location: 'Tegal, Indonesia',
  email: 'setyaardikurniawan123@gmail.com',
  phone: '+62 877 1104 3628',
  linkedin: 'http://www.linkedin.com/in/setya-ardi-kurniawan-714563430',
  github: 'https://github.com/setyaardik',
  formEndpoint: 'https://formspree.io/f/mkjnqwqa',
  typewriter: [
    'Fullstack Developer',
    'React Developer',
    'Node.js Developer',
    'UI/UX Enthusiast',
  ],
  summary:
    'Fullstack developer yang masih terus belajar membangun aplikasi web end-to-end. Terbiasa mengerjakan project pakai React, Go, Django, dan Laravel, dengan PostgreSQL dan MySQL untuk urusan data. Lebih suka menulis kode yang jelas dan mudah dipahami daripada yang terlihat rumit.',
  skills: [
    { name: 'React', level: 90, icon: 'react' },
    { name: 'TypeScript', level: 85, icon: 'ts' },
    { name: 'JavaScript', level: 90, icon: 'js' },
    { name: 'Node.js', level: 80, icon: 'node' },
    { name: 'Go', level: 70, icon: 'go' },
    { name: 'Django', level: 75, icon: 'django' },
    { name: 'Tailwind CSS', level: 88, icon: 'tailwind' },
    { name: 'Flutter', level: 70, icon: 'flutter' },
    { name: 'PostgreSQL', level: 70, icon: 'postgres' },
    { name: 'MySQL', level: 70, icon: 'mysql' },
    { name: 'Prisma', level: 72, icon: 'prisma' },
  ],
  tools: [
    'GitHub',
    'Docker',
    'Figma',
    'Redux',
    'Prisma',
    'REST API',
    'JWT Auth',
    'Vite',
  ],
  marquee: [
    'Fullstack Developer',
    'React',
    'Flutter',
    'Node.js',
    'TypeScript',
    'Go',
    'Django',
    'PostgreSQL',
    'MySQL',
    'Tailwind CSS',
    'Prisma',
  ],
  projects: [
    {
      title: 'Sistem Antrian Cuci Kendaraan',
      description:
        'Sistem antrian cuci kendaraan lengkap: pelanggan cek antrian dari link publik, admin kelola antrian dan status kendaraan secara real-time.',
      tech: ['Go', 'React', 'Tailwind CSS'],
      github: '#',
      demo: 'https://cuci-mobil-profile.pages.dev/cek-antrian',
      image: '',
      images: ['/karya/cuci-kendaraan/1.png', '/karya/cuci-kendaraan/2.png'],
      featured: true,
    },
    {
      title: 'Landing Page 34 Anjungan PT PRPP Jawa Tengah',
      description:
        'Landing page resmi 34 anjungan PT PRPP Jawa Tengah sebagai sarana informasi dan promosi proyek anjungan.',
      tech: ['React', 'Bootstrap', 'Tailwind CSS'],
      github: 'https://github.com/setyaardik/landingpage.git',
      demo: 'https://qrgm.prppjawatengah.com/',
      image: '',
      images: ['/karya/landingpage/1.png', '/karya/landingpage/2.png'],
      featured: true,
    },
    {
      title: 'Senandung Asa',
      description:
        'Website resmi Senandung Asa — platform informasi dan kegiatan yang dibangun dengan Laravel.',
      tech: ['Laravel', 'Tailwind CSS', 'MySQL'],
      github: 'https://github.com/setyaardik/senandung-asa.git',
      demo: 'https://senandungasa.net',
      image: '',
      images: ['/karya/senandungasa/1.png'],
      featured: true,
    },
    {
      title: 'Simple LMS',
      description:
        'Backend Learning Management System sederhana: manajemen kursus, materi, tugas, dan penilaian belajar.',
      tech: ['Python', 'Django'],
      github: 'https://github.com/setyaardik/Ujian-Akhir-PSS.git',
      demo: '',
      image: '',
      images: ['/karya/simple_lms/1.png', '/karya/simple_lms/w.png'],
      featured: false,
    },
    {
      title: 'E-commerce Blangkis',
      description:
        'Aplikasi e-commerce mobile dengan katalog produk, keranjang belanja, dan alur checkout.',
      tech: ['Flutter', 'Dart'],
      github: '#',
      demo: '',
      image: '',
      images: ['/karya/blankis/1.png', '/karya/blankis/2.png'],
      featured: false,
    },
    {
      title: 'Movie App',
      description:
        'Aplikasi film full-stack: cari dan lihat info film di frontend, dengan API backend Django dan didocker-kan.',
      tech: ['React', 'Django', 'Docker'],
      github: '#',
      demo: '',
      image: '',
      featured: false,
    },
    {
      title: 'QuickTix',
      description:
        'Aplikasi pemesanan tiket event: backend Go dengan API, frontend React, dan database terpisah.',
      tech: ['Go', 'React', 'PostgreSQL'],
      github: '#',
      demo: '',
      image: '',
      featured: false,
    },
    {
      title: 'Ticketing App Capstone',
      description:
        'Aplikasi tiket untuk capstone course berbasis Laravel — kelola tiket dan transaksi pemesanan.',
      tech: ['Laravel', 'Tailwind CSS', 'MySQL'],
      github: 'https://github.com/setyaardik/CapstoneBIMKAR.git',
      demo: '',
      image: '',
      featured: false,
    },
    {
      title: 'Tiketin Aja',
      description:
        'Aplikasi pencarian dan pemesanan tiket pesawat: pilih rute, cek jadwal, dan lihat pemesanan dengan peta dan grafik.',
      tech: ['React', 'Tailwind CSS', 'Vite'],
      github: 'https://github.com/setyaardik/psk.git',
      demo: '',
      image: '',
      featured: false,
    },
    {
      title: 'Project Board',
      description:
        'Aplikasi papan kerja (kanban) real-time: autentikasi lengkap, drag & drop kolom, dan kolaborasi tim via Socket.io.',
      tech: ['Next.js', 'TypeScript', 'Prisma', 'Tailwind CSS', 'Socket.io'],
      github: '#',
      demo: '',
      image: '',
      featured: false,
    },
  ],
  certificates: [
    {
      title: 'AI Literacy for Everyone: Understand, Apply, Create',
      issuer: 'BASS Training Center & Consultant',
      year: '2025',
      file: '/sertif-ai.pdf',
      preview: '/sertif-ai-preview.jpg',
    },
    {
      title: 'Sertifikasi Kompetensi Pengembang Web (BNSP)',
      issuer: 'BNSP — LSP Universitas Dian Nuswantoro',
      year: '2026',
      file: '/sertif-web.pdf',
      preview: '/sertif-web-preview.jpg',
    },
  ],
  experience: [
    {
      role: 'Web Developer Intern',
      company: 'PT PRPP Jawa Tengah',
      period: 'Feb 2025 - Mar 2025',
      description:
        'Membangun dan memelihara fitur website perusahaan, kolaborasi dengan tim internal, dan belajar alur pengembangan produk web secara nyata.',
    },
  ],
  education: [
    {
      school: 'Universitas Dian Nuswantoro',
      degree: 'S1 Teknik Informatika',
      period: '2022 - 2026',
      gpa: '3.4',
      description:
        'Mahasiswa Teknik Informatika yang fokus mendalami web development full-stack dan aktif di komunitas pengembangan teknologi kampus.',
    },
  ],
}

export const navLinks = [
  { label: 'Home', href: '#home' },
  { label: 'About', href: '#about' },
  { label: 'Skills', href: '#skills' },
  { label: 'Projects', href: '#projects' },
  { label: 'Experience', href: '#experience' },
  { label: 'Sertifikat', href: '#sertifikat' },
  { label: 'Contact', href: '#contact' },
]
